on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_x86_64_artifact:
    runs-on: ubuntu-latest
    container:
      image: alpine:edge
      options: --user root
    name: Build abuild (x86_64)
    steps:
      - uses: actions/checkout@v2.1.0
      - run: |
          apk update
          apk add bash curl build-base openssl-libs-static zlib-static openssl1.1-compat-dev zlib-dev openssl-dev
          curl -L "https://raw.githubusercontent.com/stdcurse/abuild/main/build" | bash
          mv /artifacts .
      - uses: actions/upload-artifact@master
        with:
          name: x86_64
          path: artifacts/x86_64/abuild-x86_64.tar.gz
  build_aarch64_artifact:
    runs-on: ubuntu-18.04
    name: Build abuild (aarch64)
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: alpine_latest
          githubToken: ${{ secrets.GTOKEN }}
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            apk update
            apk add bash curl build-base openssl-libs-static zlib-static openssl1.1-compat-dev zlib-dev openssl-dev
            curl -L "https://raw.githubusercontent.com/stdcurse/abuild/main/build" | bash
      - uses: actions/upload-artifact@master
        with:
          name: aarch64
          path: artifacts/aarch64/abuild-aarch64.tar.gz
  do_release:
    runs-on: ubuntu-latest
    needs: [build_aarch64_artifact, build_x86_64_artifact]
    name: Create release
    steps:
      - run: mkdir artifacts
      - uses: actions/download-artifact@master
        with:
          name: aarch64
          path: artifacts/abuild-aarch64.tar.gz
      - uses: actions/download-artifact@master
        with:
          name: x86_64
          path: artifacts/abuild-x86_64.tar.gz
      - run: find
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/abuild-aarch64.tar.gz,artifacts/abuild-x86_64.tar.gz"
          token: ${{ secrets.GTOKEN }}
          tag: ${{ github.ref_name }}.${{ github.sha }}
