on: [push, pull_request]
jobs:
  build_aarch64_artifact:
    runs-on: ubuntu-18.04
    name: Build abuild (aarch64)
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: alpine_latest
          githubToken: ${{ secrets.GTOKEN }}
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            apk update
            apk add bash curl
            curl -L "https://raw.githubusercontent.com/stdcurse/abuild/main/build" | bash
      - name: Show
        run: |
          ls -al "${PWD}/artifacts"
